# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  ecom-ex01:
    image: ecom-ex01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db1
volumes:
  mongodata: